on:
  workflow_dispatch:

name: Fetch All Secrets from AWS Secrets Manager

permissions:
  id-token: write
  contents: read  

jobs:
  fetch-secrets:
    name: Fetch Secrets
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::214580919421:role/GitHubOIDCRole
          aws-region: us-east-1

      - name: Export temporary credentials to ENV file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          filename: .env
        env:
          AWS_ACCESS_KEY_ID: ${{ steps.configure-aws-credentials.outputs.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.configure-aws-credentials.outputs.aws-secret-access-key }}
          AWS_SESSION_TOKEN: ${{ steps.configure-aws-credentials.outputs.aws-session-token }}
          AWS_REGION: us-east-1
          
      - name: Print exported AWS credentials (.env)
        run: cat .env
      - name: Fetch All Secrets from AWS Secrets Manager
        id: list-secrets
        run: |
          echo "Fetching all secrets..."
          SECRET_LIST=$(aws secretsmanager list-secrets --query 'SecretList[*].Name' --output json | jq -c)
          echo "SECRET_LIST=$SECRET_LIST" >> $GITHUB_ENV
      - name: Fetch and Print Secret Values
        run: |
          echo "Fetching secret values..."
          for SECRET in $(echo "$SECRET_LIST" | jq -r '.[]'); do
            SECRET_VALUE=$(aws secretsmanager get-secret-value --secret-id "$SECRET" --query SecretString --output text)
            echo "Secret Name: $SECRET"
            echo "Secret Value: $SECRET_VALUE"
          done
